USE [master]
GO

/****** Object:  Database [DemoDB]    Script Date: 07/03/2015 08:08:20 ******/
CREATE DATABASE [DemoDB] ON  PRIMARY 
( NAME = N'DemoDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\DemoDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DemoDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\DemoDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DemoDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DemoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoDB] SET  READ_WRITE 
GO

ALTER DATABASE [DemoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DemoDB] SET  MULTI_USER 
GO

ALTER DATABASE [DemoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoDB] SET DB_CHAINING OFF 
GO





USE [DemoDB]
GO

/****** Object:  Table [dbo].[Person]    Script Date: 07/03/2015 08:07:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Person](
	[PersonID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[MiddleName] [nvarchar](50) NULL,
	[Gender] [char](1) NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Person]  WITH CHECK ADD  CONSTRAINT [CK_Person_Gender] CHECK  (([Gender]='O' OR [Gender]='U' OR [Gender]='F' OR [Gender]='M'))
GO

ALTER TABLE [dbo].[Person] CHECK CONSTRAINT [CK_Person_Gender]
GO


USE [DemoDB];
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

SET IDENTITY_INSERT [dbo].[Person] ON;

BEGIN TRANSACTION;
INSERT INTO [dbo].[Person]([PersonID], [FirstName], [LastName], [MiddleName], [Gender])
SELECT 1, N'John', N'Pupkin', NULL, N'M' UNION ALL
SELECT 2, N'Tester', N'Testerson', NULL, N'M'
COMMIT;
RAISERROR (N'[dbo].[Person]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

SET IDENTITY_INSERT [dbo].[Person] OFF;

